### ISSUE TITLE
[Add Check]: cell and sample id

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwbinspector#103]
### What would you like to see added to the NWBInspector?

@satra has requested checks for more complete metadata associated with intracellular electrophysiology patch clamp experiments, including checking for cell and sample ids.

### Do you have any interest in helping implement the check function?

Yes, but I would need guidance.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this check was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by CodyCBakerPhD** [comment]
One tricky thing for this is I think it relies on the dandi icephys extension, so not entirely sure if it ought to be included in our core offering (through fancier autoloading for extensions) or if it all ought to exist on the DANDI side.
