### ISSUE TITLE
[New Check]: Check Subject age or dob

### ISSUE THREAD

**Issue by luiztauffer** [NeurodataWithoutBorders/nwbinspector#112]
### What would you like to see added to the NWBInspector?

I'm getting this:
```
1.1.2   Subject 'subject' located in ''
        check_subject_age: Subject is missing age.
```

even if the Subject has `date_of_birth` defined. 
I think `check_subject_age` should be changed to `check_subject_age_or_dob`

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this feature was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by CodyCBakerPhD** [comment]
From first line of [Subject Best Practices](https://nwbinspector.readthedocs.io/en/dev/best_practices/nwbfile_metadata.html#subject): "It is recommended to always include as many details about the experimental subject as possible."

I'll take that to mean that if you have the information available to fill in an available field, then it should be filled.

Age & DOB indeed have this special potential where if one of them is known, the other can be inferred in conjunction with the `session_start_time`. I'd be open to adding some extra conditional details to `message` of [check_subject_age](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/nwbinspector/checks/nwbfile_metadata.py#L37) informing the user both that it can be inferred from DOB + `session_start_time` in that way, and even explicitly what it should be in ISO 8601 format.

I'd also agree to a similar check for if DOB is specified and the extra check if it can be inferred from age + `session_start_time`.

I notice you'd be interesting in implementing this; do you have any questions about how to do so?

**Comment by bendichter** [comment]
@luiztauffer you are right, we should not require both
