### ISSUE TITLE
[Add Check]: Slashes in object names

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwbinspector#113]
### What would you like to see added to the NWBInspector?

Check that the `name` field of all objects does not include slashes ('/' or '\\').

Not really sure what the `neurodata_type` should be for this, though. Maybe have it act on anything that is a subclass of a NWBContainer, and then the logic of the test scans all the items inside that container?

Or just have it be a recursive function that starts at the NWBFile container level and then recurses down any objects that are themselves containers?

It's already in the Best Practices: towards the bottom of https://nwbinspector.readthedocs.io/en/dev/best_practices/naming.html#neurodata-types (which will get cleaned up in the next week)

### Do you have any interest in helping implement the check function?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this check was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by bendichter** [comment]
This should act on `NWBContainer`
