### ISSUE TITLE
[Feature]: conda-forge feedstock

### ISSUE THREAD

**Issue by yarikoptic** [NeurodataWithoutBorders/nwbinspector#116]
### What would you like to see added to the NWBInspector?

In light of nwbinspector becoming a dependency of dandi-cli in https://github.com/dandi/dandi-cli/, nwbinspector better becomes available for `conda` distribution within `conda-forge` channel so we would be able to continue having `dandi` client package there for the next release too.

@jwodder , since you have experience with creating feedstock recipes, would you be so kind to prepare one for nwbinspector?

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this feature was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by CodyCBakerPhD** [comment]
We use an automated GitHub Action to perform our PyPI upload with every new release; would something like that be possible with conda-forge?

**Comment by jwodder** [comment]
@CodyCBakerPhD: No.  Releases with conda-forge are performed using conda-forge's own automation:

* Once the PR to conda-forge/staged-recipes is accepted, a new repository is created in the conda-forge organization for the project
* A bot regularly checks for new releases of the source package on PyPI
* New PyPI releases cause a PR to be created in the project's conda-forge repository that updates the sdist link and version number
* Once the PR is merged, the CI takes care of releasing to conda-forge

**Comment by CodyCBakerPhD** [comment]
@jwodder Released new version and pinned on integration PR: https://github.com/dandi/dandi-cli/pull/941#discussion_r845306413

Did you want us to make the PR on conda-forge for the feedstock, or were you going to do that for us?

**Comment by jwodder** [comment]
conda-forge PR created: https://github.com/conda-forge/staged-recipes/pull/18618

**Comment by CodyCBakerPhD** [comment]
All done now!
