### ISSUE TITLE
[Documentation]: MatNWB UUID alternative?

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwbinspector#127]
### What would you like changed or added to the documentation and why?

@bendichter or @lawrence-mbf In the Best Practices for the NWBFile `identifier`, I instruct PyNWB users towards the UUID project. What is the supported analog in MatNWB and do you have a link to a tutorial or other instructions that I can include?

### Do you have any interest in helping write or edit the documentation?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this change was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by lawrence-mbf** [comment]
For UUID MatNWB just uses `java.util.UUID.randomUUID().toString()` internally. Not sure if there are MATLAB packages that are better.

**Comment by CodyCBakerPhD** [comment]
@lawrence-mbf Thanks! That's all I needed
