### ISSUE TITLE
[Documentation]: Coordinate description for Allen CCF v3

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwbinspector#128]
### What would you like changed or added to the documentation and why?

The current Best Practices (ported from the old ones): https://nwbinspector.readthedocs.io/en/dev/best_practices/ecephys.html#anatomical-coordinates

indicates that for Allen Institute CCF v3, (+x = posterior, +y = inferior, +z = right).

1. Is there a documentation I can link specifically to this for the x/y/z conventions? I'm currently only linking to the general CCF page there.
2. 'right' seems subjective to a dorsal or ventral view, is there a better way we can phrase that?

### Do you have any interest in helping write or edit the documentation?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this change was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by bendichter** [comment]
Right refers to the subject's right, e.g. "right hemisphere"

**Comment by bendichter** [comment]
I don't remember how we decided on the coordinates convention

**Comment by CodyCBakerPhD** [comment]
Thanks, that clarifies.
