### ISSUE TITLE
[Add Check]: no data entry should be a dictionary

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwbinspector#156]
### What would you like to see added to the NWBInspector?

We've seen cases where a Python dictionary is dumped directly into a data field of a table field that was allowed to be a string. These should instead be added as separate custom rows/columns to the table.

While it would be possibly to detect this with a simple `try`/`except` around a `dict` cast of the `str` value, it might be better practice and more performant to use a simple regex like below. 

### Pseudocode or other logic of the check

```shell
for data_element in data:
    re.findall(data_element, r"{.*?}")  # need to improve, obviously. Possibly "{".*?" : .*?}"? I'll test it a bit
```

### Do you have any interest in helping implement the check function?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this check was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by bendichter** [comment]
What about https://stackoverflow.com/a/3845829/2559070?
