### ISSUE TITLE
[Add Check]: identifier field is unique across folder

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwbinspector#157]
### What would you like to see added to the NWBInspector?

An interesting test this would be; it is certainly a Best Practice that the `identifier` be unique to each individual NWBFile, but checks in the NWBInspector are designed to be run on single NWBFiles only. Will have to think about how to do this when calling the CLI on a folder or `inspect_all` on a folder path.

### Pseudocode or other logic of the check

```shell
assert len(set(identifiers_from_nwbfiles_in_folder)) == len(list_of_nwbfiles)
```

### Do you have any interest in helping implement the check function?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this check was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by bendichter** [comment]
Maybe something like 

```python
IDENTIFIERS = []

def check_unique_identifier(NWBFile):
    if NWBFile.identifier in IDENTIFIERS:
        return InspectorMessage(...)
    else:
        IDENTIFIERS.append(NWBFile.identifier)

```

though that might not work if you are parallelizing

**Comment by CodyCBakerPhD** [comment]
In principle it *should* work fine with parallelization (both processes and threading) since they share the global variable space and a list or strings is pickleable.

Two things about that approach we would need to be careful about...

(1) not an issue for CLI, but when running as as library, we would need a mechanism for resetting the `IDENTIFIERS` if running any `inspect_*` function more than once, such as `inspect_all` on two separate non-recursive folders. We could just define `global IDENTIFIERS` at the top, then set `IDENTIFIERS=[]` inside each `inspect_*` function, but that seems an excessive and uncontained solution - it also doesn't seem as if it would scale well if we ever wanted to add more folder-wide checks like this.

I guess solution would be to have private functions like `_reset_global_checks` and `_init_global_checks` that served as the centralized place for all such variables, and these get called before and after all inspections.

(2) this ID-specific approach will return one message per non-unique occurrence - while these might be aggregated by the generalized formatting, we would need to be careful there that the `message` field of the NWBInspector does not use file-specific f-strings/ I was originally imagining a single kind of 'pre-check' that only ran once (and only in `inspect_all`, and grabbed all the values from all the `nwbfiles` in one shot. But I guess this approach might fit better into our pre-existing unit-check structure.
