### ISSUE TITLE
[Feature]: run command line on dandi hub

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwbinspector#165]
### What would you like to see added to the NWBInspector?

I'd like to run in Terminal:

```bash
nwbinspector https://dandiarchive.org/dandiset/000231/draft
```

and have nwbinspector automatically set up the streaming to inspect the dandiset in the cloud

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this feature was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by CodyCBakerPhD** [comment]
Happy to include this in the PR for issue #154 ; just about have a dev branch working for it, will open a PR by Monday.

**Comment by bendichter** [comment]
sounds good!
