### ISSUE TITLE
[Add Check]: ophys checks to add

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwbinspector#17]
* [ ]  image_mask dimensions do not match dimensions of associated ImageSeries
* [x] wavelength is not in nm

**Comment by CodyCBakerPhD** [comment]
@bendichter So now it's just the 2nd one, 

> image_mask dimensions do not match dimensions of associated ImageSeries

that is left, right?

**Comment by bendichter** [comment]
yeah
