### ISSUE TITLE
[Feature]: lru caching for repeated table column data access

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwbinspector#177]
### What would you like to see added to the NWBInspector?

Not a huge deal, but I notice it might increase performance on various dandisets to reduce the number of repeated data access operations by the table checks (or anything else that extracts the same limited amount of data across multiple checks).

We had previously hypothesized lru caching for this, so adding it to the to-do list.

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this feature was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by bendichter** [comment]
Good idea! Try 

https://docs.python.org/3/library/functools.html#functools.cache

It might be tricky to make the inputs hashable. Maybe something like 

```python
@functools.cache
def get_dataset_values(uuid, dataset_name, slice):
    ...
```
