### ISSUE TITLE
[Feature]: adjust test coverage to not include test folder

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwbinspector#179]
### What would you like to see added to the NWBInspector?

It looks like the codecov report is including the test in its line count. Would it be possible to change the coverage to just the package?

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this feature was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by CodyCBakerPhD** [comment]
It shouldn't be: https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/codecov.yml#L18

Weird, I'll look into it

**Comment by CodyCBakerPhD** [comment]
Are you sure? It's not displaying on the main page: https://app.codecov.io/gh/neurodatawithoutborders/nwbinspector

**Comment by CodyCBakerPhD** [comment]
Or on specific branches: https://app.codecov.io/gh/neurodatawithoutborders/nwbinspector/branch/spatial_series_dims

**Comment by CodyCBakerPhD** [comment]
However, it does appear as if there was a legacy mistake in the codecov settings for the repo that treated the default comparison and display branch as 'master' instead of 'dev'.

Fixed that: https://app.codecov.io/gh/NeurodataWithoutBorders/nwbinspector/

**Comment by bendichter** [comment]
you got it! thanks!
