### ISSUE TITLE
[Feature]: Save report file even if no violations or suggestions were found

### ISSUE THREAD

**Issue by luiztauffer** [NeurodataWithoutBorders/nwbinspector#186]
### What would you like to see added to the NWBInspector?

if the `--report-file-path` options is used, I believe we should generate the report file even if no violations or suggestions were found.
For example, I ran this command:
```
nwbinspector --report-file-path report.txt --threshold BEST_PRACTICE_VIOLATION --detailed .
```
which took a long time to finish (lots of files at `.` with lots of timeseries fields), and got me confused when I couldn't find the report. Running it without the threshold generated a report with some suggestions.

It could preserve the same header:
```
**************************************************
NWBInspector Report Summary

Timestamp: 2022-04-18 11:30:55.716249+02:00
Platform: Linux-5.11.0-46-generic-x86_64-with-glibc2.17
NWBInspector version: 0.3.9

Found 0 issues over 68 files
**************************************************
```

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this feature was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by bendichter** [comment]
good idea
