### ISSUE TITLE
[Documentation]: Should subject.strain specify sub-species?

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwbinspector#194]
### What would you like changed or added to the documentation and why?

The current Best Practice for [specifying sub-species of Subjects](https://nwbinspector.readthedocs.io/en/dev/best_practices/nwbfile_metadata.html#species) indicates to append sub-species information after a dash separation.

This is mainly motivated by our previous usage in the Buzsaki datasets to specify the Long Evans type, *e.g.*, `subject.species = "Rattus norvegicus - Long Evans"`.

However, [reading on how this subspecies came to b](https://janvier-labs.com/en/fiche_produit/long-evans_rat/#:~:text=The%20LONG%20EVANS%20rat%20is,small%20and%20resistant%20to%20oncogenesis.)e, it uses the keyword `strain` to refer to it. The [NWB Schema for subject](https://nwb-schema.readthedocs.io/en/latest/format.html?highlight=subject#subject) has a `strain` field, so I wonder if the Best Practice should be to use that instead of the dash in the main `species` field?

@bendichter What do you think?

### Do you have any interest in helping write or edit the documentation?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this change was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by rly** [comment]
Yes. Long Evans is a strain (as well as Sprague-Dawley and Wistar). C57BL/6 is a common mouse strain.
