### ISSUE TITLE
[Add Check]: Images.order_of_images should map 1 to 1 to Image objects in Images

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwbinspector#211]
### What would you like to see added to the NWBInspector?

NWB 2.5 will introduce a new dataset for `Images` named "order_of_images" which specifies the order of the images within the `Images` object.

We should check:
1. "order_of_images" contains references to all of the images only once that are in the `Images` object
2. "order_of_images" contains no other images (e.g., from another object)

### Pseudocode or other logic of the check

```shell
if an NWBFile contains an Images object, then
create a set with the names of the Image objects in the Images object
create a set with the names of the Image objects referenced by "order_of_images"
check that the two sets are equal
```

### Do you have any interest in helping implement the check function?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this check was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by bendichter** [comment]
Thanks for filing this, @rly. This seems pretty straightforward, and we will be happy to implement it as soon as 2.5 is released.

**Comment by oruebel** [comment]
> 1. "order_of_images" contains references to all of the images only once that are in the `Images` object

Is ``order_of_images`` required to have the same length as the number of images stored in Images? If so,m that should probably another check. Also, if ``order_of_images`` is intended to only provide a unique order of the images without repeats---compared to e.g., allowing users to create a randomized order of images where the same image may be repeated several times---then I think we should expand on the doc of ``order_of_images`` in the schema to clarify this constraint.
