### ISSUE TITLE
[Bug]: names not working

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwbinspector#216]
### What happened?

```
MacBook-Pro-5:dev bendichter$ nwbinspector --config dandi /Users/bendichter/Downloads/09_35_09.nwb
                                                                                                                            

**************************************************
NWBInspector Report Summary

Timestamp: 2022-07-01 09:15:52.790617-04:00
Platform: macOS-10.16-x86_64-i386-64bit
NWBInspector version: 0.4.6

Found 8 issues over 1 files:
       8 - BEST_PRACTICE_SUGGESTION
**************************************************


0  BEST_PRACTICE_SUGGESTION
===========================

0.0  /Users/bendichter/Downloads/09_35_09.nwb: None - 'None' object with name 'None'
       Message: Description is missing.

0.1  /Users/bendichter/Downloads/09_35_09.nwb: None - 'None' object with name 'None'
       Message: Description ('no description') is a placeholder.

0.2  /Users/bendichter/Downloads/09_35_09.nwb: None - 'None' object with name 'None'
       Message: data is not compressed. Consider enabling compression when writing a dataset.

0.3  /Users/bendichter/Downloads/09_35_09.nwb: None - 'None' object with name 'None'
       Message: Experimenter is missing.

0.4  /Users/bendichter/Downloads/09_35_09.nwb: None - 'None' object with name 'None'
       Message: Experiment description is missing.

0.5  /Users/bendichter/Downloads/09_35_09.nwb: None - 'None' object with name 'None'
       Message: Metadata /general/institution is missing.

0.6  /Users/bendichter/Downloads/09_35_09.nwb: None - 'None' object with name 'None'
       Message: Metadata /general/keywords is missing.

0.7  /Users/bendichter/Downloads/09_35_09.nwb: None - 'None' object with name 'None'
       Message: Subject age, '24-48 hrs', does not follow ISO 8601 duration format, e.g. 'P2Y' for 2 years or 'P23W' for 23 weeks.
```

### Operating System

macOS

### Python Executable

Conda

### Python Version

3.9

### Usage

Command Line Interface

### Were you streaming with ROS3?

No

### Package Versions

attrs==21.4.0
certifi @ file:///private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_83242e7e-f82d-4a71-8ef2-9d71d212d249gu_wxmeq/croots/recipe/certifi_1655968827803/work/certifi
click==8.1.3
h5py==3.7.0
hdmf==3.3.2
jsonschema==4.6.1
natsort==8.1.0
numpy==1.21.6
-e git+https://github.com/NeurodataWithoutBorders/nwbinspector.git@7a4481ff62caa9d177f890b27cee6a3bb63a71c0#egg=nwbinspector
packaging==21.3
pandas==1.4.3
pynwb==2.0.1
pyparsing==3.0.9
pyrsistent==0.18.1
python-dateutil==2.8.2
pytz==2022.1
PyYAML==6.0
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.6
scipy==1.8.1
six==1.16.0
tqdm==4.64.0

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/neurodatawithoutborders/nwbinspector/issues)?
- [X] To the best of your ability, have you ensured this is a bug within the code that checks the NWBFile, rather than a bug in the NWBFile reader (e.g., [PyNWB](https://github.com/NeurodataWithoutBorders/pynwb) or [MatNWB](https://github.com/NeurodataWithoutBorders/matnwb))?

**Comment by CodyCBakerPhD** [comment]
Thanks for attaching all the system information!

After requesting you to try NOT using the `--config` flag, the behavior was as expected.

Looks like a related issue to https://github.com/NeurodataWithoutBorders/nwbinspector/issues/108
