### ISSUE TITLE
[Add Check]: Add Best Practice for External Mode usage for ImageSeries

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwbinspector#258]
### What would you like to see added to the NWBInspector?

Came up in meeting today - add best practice section covering external mode usage for natural behavioral videos saved as ImageSeries.

### Do you have any interest in helping implement the check function?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this check was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin did you want to take this one?

**Comment by h-mayorquin** [comment]
I could, but where is the file that should be modified? Where does it live? 
Where is the repo for?
https://www.nwb.org/best-practices/

**Comment by CodyCBakerPhD** [comment]
@h-mayorquin These are the actual current Best Practices: https://nwbinspector.readthedocs.io/en/dev/best_practices/best_practices_index.html

They are in the docs for this repo, let me know if you have trouble finding them.

@oruebel Should we replace the https://www.nwb.org/best-practices/ with a link to https://nwbinspector.readthedocs.io/en/dev/best_practices/best_practices_index.html?

**Comment by oruebel** [comment]
@CodyCBakerPhD my best guess is that the issue is that even though  https://www.nwb.org/best-practices/ is no longer linked to from the website, Google still finds it as the top hit when searching for "NWB Best Practices". Unfortunately we can't hack the Google search. I'll update the old page on nwb.org to point to the best practice on the the NWB Inspector docs.

**Comment by CodyCBakerPhD** [comment]
> my best guess is that the issue is that even though https://www.nwb.org/best-practices/ is no longer linked to from the website, Google still finds it as the top hit when searching for "NWB Best Practices".

Ahhhh, that'll do it.

Thanks for checking!

**Comment by oruebel** [comment]
@CodyCBakerPhD I've now updated https://www.nwb.org/best-practices/ Please have a look and let me know if there are any further changes that I should make.

**Comment by oruebel** [comment]
I've now also added on nwb.org a link to the "Best Practices for NWB Data" to the [overview of NWB Policies page](https://www.nwb.org/policies-overview/) as well as in main menu as part of the Policies sub-menu. Hopefully that will help clarify this issue further and make the best practices easier to find from the nwb.org website:

<img width="1467" alt="Screen Shot 2022-08-30 at 12 09 10 PM" src="https://user-images.githubusercontent.com/10999845/187523309-17b3605d-d6d5-4815-8868-4a44f1e4f31f.png">

**Comment by h-mayorquin** [comment]
So, if the file_path of the nwb file is:
`/the/path/of/the/nwbfile/file.nwb"
The path of the ImageSeries data should be what?
1. `nwbfile/movie.avi`
2. `/movie.avi`
3. `movie/avi`

Which one? And where is this requirements coming from?

**Comment by CodyCBakerPhD** [comment]
The path attached to the ImageSeries should be `external_file=["./<relative_path_to_avi_file_from_nwb_file>"]`. I agree that giving an explicit example in the BP section might help.

As far as where the `.avi` file ought to be stored relative to the NWB file, I'd add a minor suggestion that it be kept adjacent for sharing purposes (and DANDI does this automatically when organizing a dataset). But I don't think storage location itself should be something we check for or even require as the main spirit of the BP.

> Which one? And where is this requirements coming from?

For the same reason DANDI enforces it - an absolute path on one persons system will almost certainly not be a valid path on the system of anyone you want to share your file(s) with.

**Comment by CodyCBakerPhD** [comment]
And on the justification of using external mode over writing it as a dataset - it's because no HDF5 compression plugin does as good of a job at reducing file sizes for natural movies. There are also some legal licensing reasons why we can't just implement a fancy movie codec into HDF5, too (they're almost all restrictive I believe).

Now something that came up with the Talmo lab as a way around this is - one could technically write the raw byte stream directly to the NWB file and this would resolve the compression issue... The problem is that the PyNWB API would then have to offer native way of decoding the byte stream, which it came up in conversation is simply beyond the scope of what we would be able to support. Otherwise, you'd have data contained in an NWB file that requires an external parser (like OpenCV) to allow access to the data, which is not very user friendly and would also require a lot of tutorial/explanation to use.

**Comment by h-mayorquin** [comment]
> The path attached to the ImageSeries should be `external_file=["./<relative_path_to_avi_file_from_nwb_file>"]`. I agree that giving an explicit example in the BP section might help.

This is not clear to me, can you write an examples? Do you mean relative to parent directory of the nwbfile? 

By adjacent you mean in the same directory, right?

**Comment by h-mayorquin** [comment]
Concerning the explanation:
Are you saying that the plugin to compress movies exists right now but that we don't use because of licencing issues? Because, if the plugging does not exists but we could in principle implement it or go around the licencing in someway then telling that to the final user sounds convoluted to me. They don't need to know the reasons why something is not implemented.

**Comment by CodyCBakerPhD** [comment]
"adjacent" -> same parent directory, the files are 'side-by-side'

Relevant example: you recently shared with me an NWB file (`courtship_behavior_LC10a_fly5.nwb`) that contained an ImageSeries in acquisition (`Video: 161101_10a05`) written in external mode, with the file path being `/home/heberto/Murthy-data-share/one2one-mapping/raw_data/courtship_behavior/videos/161101_10a05.avi`.

My main system (Windows platform) does not (a) specify base volume as `/` (a drive such as `E:/` is instead required; `~` could arguably be used as a pseudo-relative base but that can differ over platforms...), (b) even if I was on a linux device, I wouldn't have a `heberto` folder in my `home` directory. So the NWB file now in effect has a broken link after sharing, but if it had been a relative path you could have shared with me a folder structure that maintains that relativity, or if adjacent and relative, just share both files together.

**Comment by CodyCBakerPhD** [comment]
> Are you saying that the plugin exists to compress movies exists right now but that we don't use because of licencing issues?

That is my understanding, perhaps @bendichter or @oruebel can give a more precise description.


> Because, if the plugging does not exists but we could in principle implement it

Indeed, but that's where the licensing comes in.

> or go around the licencing in someway then telling that to the final user sounds convoluted to me.

The 'go around it' is the bytestream part above, the issue is we don't think it would make for a good user experience and could result in data existing in an NWB file that the NWB API doesn't know how to parse on request. Yeah, IDK that we necessarily need to include that part in the BP since it is a bit technical, but it could be a question that occurs to some technically-minded individuals.

> They don't know need to know of the reasons why something is not implemented.

If the reason is technical, I'd agree. I don't think this is a technical issue but rather a legal one. And it's more to head off or summarize a potential FAQ of 'why shouldn't I write my video data directly into the file?', which people do deserve an explanation for.

**Comment by h-mayorquin** [comment]
> "adjacent" -> same parent directory, the files are 'side-by-side'

Thanks.

> Relevant example: you recently shared with me an NWB file (`courtship_behavior_LC10a_fly5.nwb`) that contained an ImageSeries in acquisition (`Video: 161101_10a05`) written in external mode, with the file path being `/home/heberto/Murthy-data-share/one2one-mapping/raw_data/courtship_behavior/videos/161101_10a05.avi`.
> 
> My main system (Windows platform) does not (a) specify base volume as `/` (a drive such as `E:/` is instead required; `~` could arguably be used as a pseudo-relative base but that can differ over platforms...), (b) even if I was on a linux device, I wouldn't have a `heberto` folder in my `home` directory. So the NWB file now in effect has a broken link after sharing, but if it had been a relative path you could have shared with me a folder structure that maintains that relativity, or if adjacent and relative, just share both files together.

This I understand but the question remains the same `<relative_path_to_avi_file_from_nwb_file>` does not make sense. I think you mean relative to the parent directory of the nwb file, can you confirm?

**Comment by CodyCBakerPhD** [comment]
> I think you mean relative to the parent directory of the nwb file, can you confirm?

Yes. I was thinking of it in terms of first-person navigation: 'what sequence of `cd` commands would I need to run to change my working directory *from* the place where the NWB file is *to* the place where the `.avi` file is'. Sorry if that's confusing

**Comment by h-mayorquin** [comment]
I mean, my question was probably confusing as well given your last answer. No worries, man. Thanks for clarifying all the details!
