### ISSUE TITLE
[Feature]: option to exclude tests which require network connectivity

### ISSUE THREAD

**Issue by TheChymera** [NeurodataWithoutBorders/nwbinspector#260]
### What would you like to see added to the NWBInspector?

I get a lot of errors of the form:

```
E   OSError: Unable to open file (curl cannot perform request)
```

When trying to run the test suite of versions `0.4.{3..12}` this being the full build log for the latter: https://ppb.chymera.eu/ec7618.log

This could be done by either having an option which just turns network-reliant tests off (e.g. depending on an environment variable [as seen in DANDI](https://github.com/dandi/dandi-cli/blob/17e0b04263ed48b3c2f5946b20daded49bef0dfa/dandi/tests/skip.py#L131)), or by releasing static test data which can be fetched explicitly instead of implicitly (which is the reason why tests often are and generally should be network-sandboxed). This latter option is used by ITK (not the additional release links):

![decohost_2022-09-06T15:05:49](https://user-images.githubusercontent.com/950524/188718515-0a706f35-50df-4083-902e-03465f02ffc1.png)

The band-aid solution is [to simply disable the affected tests manually `pytest ... --ignore tests/test_inspector.py --ignore tests/unit_tests`](https://ppb.chymera.eu/1b2995.log), but this is likely unsustainable as things change in future releases, so it would be cool to have something more reliable.

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this feature was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by CodyCBakerPhD** [comment]
This was 'kind of' taken care of, or at least attempted to be, by the following lines of `test_inspector.py`

https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/tests/test_inspector.py#L31-L41 and https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/tests/unit_tests/test_time_series.py#L20-L31 (with skips at https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/tests/test_inspector.py#L588 and https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/tests/unit_tests/test_time_series.py#L181-L184, for instance)

so the only way those tests were run by the suite (not skipped) is if it was confirmed that you _could_ stream _a file_ when the tests were first triggered and performed their global imports. But it appears that if something happened to connectivity after initializing the tests yet before they finished, this issue might indeed happen.

I agree this should be more generally controllable, though. I think a global variable like DANDI uses would be fine.


> releasing static test data which can be fetched explicitly instead of implicitly

Note that the tests in `test_inspector.py` are very specifically to ensure that the NWB Inspector is able to successfully resolve S3 paths and run all applications on a published DANDI set through the ros3 driver, so we really do need non-static files for that purpose. I'll grant you that the test in the `unit_test/test_time_series.py` is a very specific debug particular to a single problematic file and that one has nothing to do with streaming per se so could very well be done statically. I'll do that after allowing a global disable flag for connectivity.

**Comment by CodyCBakerPhD** [comment]
@TheChymera Does PR #261 resolve this issue?
