### ISSUE TITLE
[Feature]: update from ros3 to fsspec

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwbinspector#293]
### What would you like to see added to the NWBInspector?

fsspec has many advantages over ros3 as a streaming strategy. We should change of our streaming functionality within nwbwidgets to use fsspec instead of ros3

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this feature was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by CodyCBakerPhD** [comment]
Though I would add a note here for future reference that there's no reason to completely disallow `ros3` in case `fsspec` doesn't work in someone's particular case (also we already have infrastructure and tests for `ros3` support so might as well keep all that).

Plan is to 

(i) add `fssspec` capability here and
(ii) make it the default over `ros3`

**Comment by CodyCBakerPhD** [comment]
Well, not `fsspec`, but we did refactor to use `remfile` instead of `ros3`
