### ISSUE TITLE
[Bug]: check_electrical_series_dims is incorrect

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwbinspector#297]
### What happened?

https://github.com/NeurodataWithoutBorders/nwbinspector/blob/65fb555c584405a3afbeed2a9086020b403dd556/src/nwbinspector/checks/ecephys.py#L26-L49

This method is not quite right. It is permissible for an `ElectricalSeries` to have a different number of electrodes from the electrodes table if `ElectricalSeries.electrodes` subselects electrodes in the table

### Operating System

macOS

### Python Executable

Python

### Python Version

3.9

### Usage

Command Line Interface

### Were you streaming with ROS3?

No

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/neurodatawithoutborders/nwbinspector/issues)?
- [X] To the best of your ability, have you ensured this is a bug within the code that checks the NWBFile, rather than a bug in the NWBFile reader (e.g., [PyNWB](https://github.com/NeurodataWithoutBorders/pynwb) or [MatNWB](https://github.com/NeurodataWithoutBorders/matnwb))?

**Comment by CodyCBakerPhD** [comment]
It refers to the electrode region specifically attached to the electrical series: https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/src/nwbinspector/checks/ecephys.py#L34-L37

Perhaps `electrical_series.electrodes.data` points to the entire table? If so, how can we point to the selected subregion?

**Comment by bendichter** [comment]
I'm looking...

**Comment by bendichter** [comment]
I think you are right
