### ISSUE TITLE
[Documentation]: how to run inspection on an in-memory `NWBFile`?

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwbinspector#298]
### What would you like changed or added to the documentation and why?

I don't see anything in the docs for how to inspect an in-memory NWBFile object. Looking at the code I'm not sure it's simple to do. @CodyCBakerPhD do you think we could add this as a feature?

### Do you have any interest in helping write or edit the documentation?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this change was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by CodyCBakerPhD** [comment]
It's possible, just needs to be documented. Would simply tap into the next level of functions from the ones currently shown

**Comment by CodyCBakerPhD** [comment]
If you need the instructions right away the following should work

```python
from neuroconv import available_checks, run_checks
from pynwb import NWBHDF5IO

with NWBHDF5IO(...) as io:
    nwbfile = io.read()
    messages = list(run_checks(nwbfile=nwbfile, checks=available_checks))  # if you don't want to use it as a generator
```
