### ISSUE TITLE
checking for lazy type

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwbinspector#307]
https://github.com/NeurodataWithoutBorders/nwbinspector/blob/54ac2bc7cdcb92802b9251e29f249f155fb1ff52/src/nwbinspector/checks/time_series.py#L60

A few issues here.

1. `isinstance` can take a tuple of classes, so this line should be

```python
is_lazy_type = isinstance(time_series.data, (np.memmap, h5py.Dataset, H5Dataset))
```

2. you have `if is_lazy` and then later `if not is_lazy`. The second one should simply be `else`.

3. Why are you checking if this is lazy? Why is that relevant? Is that so you know if you can access the `.shape` attribute? Because this isn't really a good way to test for that. `np.array`s are not lazy but have the `shape` attribute. A better approach would be to use `if hasattr(data, "shape")`. Then if it's there, use it. An even better approach is to use the hdmf utility that solved all these problems already: `hdmf.utils.get_data_shape`.

**Comment by CodyCBakerPhD** [comment]
Scheduling this as a low-priority backlog following up from https://github.com/NeurodataWithoutBorders/nwbinspector/pull/296
