### ISSUE TITLE
[Add Check]: check for negative time

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwbinspector#323]
### What would you like to see added to the NWBInspector?

Check first timestamp of TimeSeries
Check for `start_time` of `TimeIntervals` table

### Do you have any interest in helping implement the check function?

Maybe.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this check was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by bendichter** [comment]
@weiglszonja fixed?

**Comment by CodyCBakerPhD** [comment]
Closed by #325
