### ISSUE TITLE
[Feature]: --version

### ISSUE THREAD

**Issue by yarikoptic** [NeurodataWithoutBorders/nwbinspector#332]
### What would you like to see added to the NWBInspector?

Print nwbinspector version when invoked with `--version` flag.  It is very common interface for **many** tools, almost a "defacto standard" of command line interfaces to have it supported.  ATM

```
❯ nwbinspector --version
Usage: nwbinspector [OPTIONS] PATH
Try 'nwbinspector --help' for help.

Error: No such option: --version (Possible options: --overwrite, --reverse, --version-id)
```

and that is after the `pip install --upgrade nwbinspector` so must be the most recent version ;)

### Do you have any interest in helping implement the feature?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this feature was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by bendichter** [comment]
@yarikoptic sure, that seems straightforward

**Comment by bendichter** [comment]
You said you have interest in helping to implement. Are you working on this now?

**Comment by yarikoptic** [comment]
doh -- it was a default I didn't change, fixed now... ATM looking into dandi upload/validation issue user reported, so unlikely would touch nwbinspector. Should indeed be straightforward
