### ISSUE TITLE
[Documentation]: `check_experimenter` link not working

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwbinspector#336]
### What would you like changed or added to the documentation and why?

https://nwbinspector.readthedocs.io/en/dev/best_practices/nwbfile_metadata.html#experimenter

### Do you have any interest in helping write or edit the documentation?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this change was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by CodyCBakerPhD** [comment]
Easy fix, name of checks changed when we split it into [check for existence](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/src/nwbinspector/checks/nwbfile_metadata.py#L51) and [check for form](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/src/nwbinspector/checks/nwbfile_metadata.py#L62) matching DANDI convention
