### ISSUE TITLE
[Discussion]: Add Error Codes?

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwbinspector#34]
As per breakout session discussion, it may be worth it to re-examine the question of associating explicit error codes to check functions.

Main point is this could (a) simplify skipping references, (b) allow us to change underlying function name but keep error code the same.

**Comment by yarikoptic** [comment]
ref: https://github.com/dandi/dandi-cli/issues/943 on need of structured records in dandi-cli validator, and where pointing to table with error codes / names in bids-validator

**Comment by CodyCBakerPhD** [comment]
We're honestly still not too convinced that this would make anything easier, and could potentially add unnecessary complexity.

For us, the _name_ of the check function (and place in the [API documentation](https://nwbinspector.readthedocs.io/en/dev/api/checks.html#nwbinspector.checks.time_series.check_regular_timestamps) interlinked with [Best Practices](https://nwbinspector.readthedocs.io/en/dev/best_practices/time_series.html#timestamps-vs-start-rate), WIP) _is_ the error code.

In particular, forming a map from an alpha-numeric registry to those checks would lose transparency by causing someone to spend the extra time to have to 'look up' what function/practice the error code maps to. And trying to make these alpha-numeric codes map 'intuitively' would be more likely subject to change over time than the names of the functions themselves.

**Comment by CodyCBakerPhD** [comment]
Old issue, closing from lack of activity
