### ISSUE TITLE
[Feature]: Expand Best practice violations?

### ISSUE THREAD

**Issue by TheChymera** [NeurodataWithoutBorders/nwbinspector#345]
### What would you like to see added to the NWBInspector?

Currently there's [only one best practice violation listed](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/801d8ec97ff238b13e8a6c30a8b8f0b419b00a93/src/nwbinspector/internal_configs/dandi.inspector_config.yaml#L9-L10), though conceptually it's of course a set and not an item. The fact that there's only one possible such “non-critical” error, makes it difficult to test error listing behaviour.

Is this something that's up to DANDI to decide — i.e. what we want to pick?
That seems a bit strange, shouldn't “best practice” be authoritatively defined by NWB and not by downstream users?

### Do you have any interest in helping implement the feature?

Yes, but I would need guidance.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this feature was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by bendichter** [comment]
@TheChymera this config changes checks from their default level. In this case, in the dandi config check_data_orientation has been downgraded from critical to a best practice violation because it should not block upload 100% of the time

**Comment by TheChymera** [comment]
@bendichter thanks for clarifying that, so this is an add-on. Is there any additional check which is a best practice violation? I assume there's a list of them in some file?

**Comment by CodyCBakerPhD** [comment]
@TheChymera

References to the checks are peppered through the Best Practices ([example](https://nwbinspector.readthedocs.io/en/dev/best_practices/time_series.html#data-orientation), at the bottom of each section 'Check function: ...')

They can all be found listed under the [API documentation](https://nwbinspector.readthedocs.io/en/dev/api/checks.html#check-functions)

You can see them all in Python, listed by default importance level with

```python
from nwbinspector import available_checks
from collections import defaultdict

checks_by_importance = defaultdict(list)
for check in available_checks:
    checks_by_importance[check.importance].append(check.__name__)
```

9 CRITICAL
24 BEST_PRACTICE_VIOLATION
17 BEST_PRACTICE_SUGGESTION

**Comment by CodyCBakerPhD** [comment]
@TheChymera Can this be closed?

**Comment by TheChymera** [comment]
Yes, thank you.
