### ISSUE TITLE
[Documentation]: Add docs page showing what is required by DANDI

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwbinspector#354]
### What would you like changed or added to the documentation and why?

Or this documentation should be provided by DANDI in their docs:
https://www.dandiarchive.org/handbook/13_upload/#data-uploadmanagement-workflow

Currently it is not clear what is required by DANDI for upload besides looking at:
https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/src/nwbinspector/internal_configs/dandi.inspector_config.yaml

### Do you have any interest in helping write or edit the documentation?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this change was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by CodyCBakerPhD** [comment]
Does this belong on the Inspector or DANDI?

**Comment by rly** [comment]
Probably DANDI now that I think about it more.
