### ISSUE TITLE
[Documentation]: show checks by importance

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwbinspector#361]
### What would you like changed or added to the documentation and why?

It would be useful for the DANDI handbook to be able to link to a page in the NWB Inspector docs that list checks by importance. We should have headings for each importance level and then a list of each check with that importance. @CodyCBakerPhD can you think of a way to automate that?

You can get this organization with the following code:

```python
from collections import defaultdict

dd = defaultdict(list)

for x in available_checks:
    dd[x.importance].append(x)
```

Is there a way of automatically generating a markdown or rst file from this?

### Do you have any interest in helping write or edit the documentation?

No.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this change was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by CodyCBakerPhD** [comment]
It's easy to do programmatically in Python; it would be the Sphinx that I'm unsure how to automatically render there

**Comment by bendichter** [comment]
Here's a start:

```python
from collections import defaultdict
import os

# Your defaultdict and available_checks
available_checks = [...]  # Replace with your actual checks
dd = defaultdict(list)

for x in available_checks:
    dd[x.importance].append(x)

# Generate the checks.rst file
doc_file = os.path.join('source', 'checks.rst')

with open(doc_file, 'w') as f:
    f.write('''Available Checks by Importance
==============================

This section lists the available checks organized by their importance level.

.. contents::
   :local:
   :depth: 1

''')

    for importance_level, checks in dd.items():
        f.write(f'''Importance Level {importance_level}
{'-' * (len(f'Importance Level {importance_level}') + 1)}

''')

        for check in checks:
            f.write(f'* :py:func:`~{check.__module__}.{check.__name__}`\n')

        f.write('\n')
```
