### ISSUE TITLE
[Bug]: HDMF 3.5.5 breaks streaming tests

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwbinspector#365]
### What happened?

As seen from daily reports: https://github.com/NeurodataWithoutBorders/nwbinspector/actions/workflows/dailies.yml

The consistent failures with the streaming tests started after the latest release of HDMF 3.5.5

@rly any idea why this would happen? See https://github.com/NeurodataWithoutBorders/nwbinspector/actions/runs/4734489840/jobs/8403485492 for instance of the failure logs

### Operating System

None

### Python Version

None

### Were you streaming with ROS3?

None

### Package Versions

<details> Copy and paste your output here </details>

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/neurodatawithoutborders/nwbinspector/issues)?
- [X] To the best of your ability, have you ensured this is a bug within the code that checks the NWBFile, rather than a bug in the NWBFile reader (e.g., [PyNWB](https://github.com/NeurodataWithoutBorders/pynwb) or [MatNWB](https://github.com/NeurodataWithoutBorders/matnwb))?

**Comment by bendichter** [comment]
We should fix this, but it also might be a good time to consider migrating streaming over to fsspec, which should not have the same issues.

**Comment by CodyCBakerPhD** [comment]
We use remfile now
