### ISSUE TITLE
[Feature]: Support HDMF Zarr backend

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwbinspector#376]
### What would you like to see added to the NWBInspector?

@CodyCBakerPhD can you help think about what would need to be done for NWB Inspector to support Zarr? Will it be just a matter of adding a flag to read different formats, or will there be more to it?

### Do you have any interest in helping implement the feature?

Maybe

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this feature was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by bendichter** [comment]
* add a flag to NWB Inspector to read Zarr files instead of the default HDF5 files
* Checks for compression might need adjustment

**Comment by rcpeene** [comment]
I'd like to second this. Just ran into a need for us to run NWBInspector on our Zarr files on codeocean

**Comment by CodyCBakerPhD** [comment]
Thanks for the ping, good timing - we plan on doing this as a part of a series of updates to the Inspector this coming month

**Comment by rcpeene** [comment]
Just checking in, what's the status here?

**Comment by CodyCBakerPhD** [comment]
Sorry, it got delayed by some other stuff. Scheduled for this month for sure
