### ISSUE TITLE
[Add Check]: rate of TimeSeries is not zero

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwbinspector#389]
### What would you like to see added to the NWBInspector?

Apparently it's possible for TimeSeries to have a rate set to `0.0`, though that makes no sense when the series has more than one frame (technically there is an edge case for ImageSeries and its variants where it can be interpreted to mean a static ophys image)

### Do you have any interest in helping implement the check function?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this check was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by bendichter** [comment]
@alessandratrapani , could you take a look at this?
