### ISSUE TITLE
[Bug]: Inspect using DANDI settings

### ISSUE THREAD

**Issue by mavaylon1** [NeurodataWithoutBorders/nwbinspector#410]
### What happened?

(NWB2) MacBook-Pro:docs mavaylon$ nwbinspector /Users/mavaylon/Research/NWB/ndx-multichannel-volume/docs/test_plane_extend.nwb --config DANDI
Traceback (most recent call last):
  File "/Users/mavaylon/opt/anaconda3/envs/NWB2/bin/nwbinspector", line 8, in <module>
    sys.exit(inspect_all_cli())
  File "/Users/mavaylon/opt/anaconda3/envs/NWB2/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/mavaylon/opt/anaconda3/envs/NWB2/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/mavaylon/opt/anaconda3/envs/NWB2/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/mavaylon/opt/anaconda3/envs/NWB2/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/mavaylon/opt/anaconda3/envs/NWB2/lib/python3.10/site-packages/nwbinspector/nwbinspector.py", line 257, in inspect_all_cli
    config = load_config(filepath_or_keyword=config)
  File "/Users/mavaylon/opt/anaconda3/envs/NWB2/lib/python3.10/site-packages/nwbinspector/nwbinspector.py", line 99, in load_config
    with open(file=file, mode="r") as stream:
FileNotFoundError: [Errno 2] No such file or directory: 'DANDI'
(NWB2) MacBook-Pro:docs mavaylon$ 

### Operating System

macOS

### Python Version

3.10

### Were you streaming with ROS3?

No

### Package Versions

Package                       Version                 Editable project location
----------------------------- ----------------------- --------------------------------------------------------------
aiohttp                       3.8.5
aiosignal                     1.3.1
airium                        0.2.5
alabaster                     0.7.13
antlr4-python3-runtime        4.9.3
anyio                         3.7.1
appdirs                       1.4.4
appnope                       0.1.3
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
arrow                         1.2.3
asciitree                     0.3.3
asttokens                     2.2.1
async-timeout                 4.0.3
attrs                         23.1.0
Babel                         2.12.1
backcall                      0.2.0
bcp47                         0.0.4
beautifulsoup4                4.12.2
bidsschematools               0.7.1
bioregistry                   0.6.108
black                         23.3.0
bleach                        6.0.0
blessed                       1.20.0
boto3                         1.28.0
botocore                      1.31.0
cachetools                    5.3.1
cattrs                        23.1.2
certifi                       2023.5.7
cffi                          1.15.1
CFGraph                       0.2.1
cfgv                          3.3.1
chardet                       5.1.0
charset-normalizer            3.1.0
ci-info                       0.3.0
class-resolver                0.4.2
click                         8.1.3
click-didyoumean              0.3.0
codespell                     2.2.4
colorama                      0.4.6
comm                          0.1.3
contourpy                     1.1.0
coverage                      7.2.5
cssutils                      2.7.1
curies                        0.5.7
cycler                        0.11.0
daff                          1.3.46
dandi                         0.55.1
dandischema                   0.8.4
dataframe-image               0.1.12
debugpy                       1.6.7
decorator                     5.1.1
defusedxml                    0.7.1
Deprecated                    1.2.14
deprecation                   2.1.0
distlib                       0.3.6
dnspython                     2.3.0
docutils                      0.18.1
EditorConfig                  0.12.3
email-validator               2.0.0.post2
entrypoints                   0.4
et-xmlfile                    1.1.0
etelemetry                    0.3.0
eutils                        0.6.0
exceptiongroup                1.1.1
executing                     1.2.0
fasteners                     0.18
fastjsonschema                2.17.1
fastobo                       0.12.2
filelock                      3.12.2
flake8                        6.0.0
fonttools                     4.40.0
fparse                        1.20.1
fqdn                          1.5.1
frozenlist                    1.4.0
fscacher                      0.3.0
funowl                        0.1.13
ghp-import                    2.1.0
google                        3.0.0
google-api-core               2.11.1
google-api-python-client      2.95.0
google-auth                   2.22.0
google-auth-httplib2          0.1.0
google-auth-oauthlib          1.0.0
googleapis-common-protos      1.59.1
graphviz                      0.20.1
greenlet                      2.0.1
gspread                       5.10.0
gspread-formatting            1.1.2
h5py                          3.8.0
hbreader                      0.9.1
hdmf                          3.9.1                   /Users/mavaylon/Research/NWB/hdmf2/hdmf
hdmf-docutils                 0.4.5
hdmf-zarr                     0.3.0.post0.dev2        /Users/mavaylon/Research/NWB/hdmf-zarr
html2image                    2.0.4.3
httplib2                      0.22.0
humanize                      4.7.0
identify                      2.5.24
idna                          3.4
ijson                         3.2.3
imageio                       2.31.3
imagesize                     1.4.1
importlib-metadata            6.7.0
iniconfig                     2.0.0
interleave                    0.2.1
ipykernel                     6.24.0
ipython                       8.14.0
ipython-genutils              0.2.0
ipywidgets                    8.0.7
isodate                       0.6.1
isoduration                   20.11.0
jaraco.classes                3.2.3
jedi                          0.18.2
Jinja2                        3.1.2
jmespath                      1.0.1
joblib                        1.3.1
jsbeautifier                  1.14.9
json-flattener                0.1.9
jsonasobj                     1.3.1
jsonasobj2                    1.0.4
jsonpatch                     1.33
jsonpath-ng                   1.5.3
jsonpointer                   2.4
jsonschema                    4.17.3
jupyter                       1.0.0
jupyter_client                8.3.0
jupyter-console               6.6.3
jupyter_core                  5.3.1
jupyter-events                0.6.3
jupyter_server                2.7.0
jupyter_server_terminals      0.4.4
jupyterlab-pygments           0.2.2
jupyterlab-widgets            3.0.8
keyring                       24.2.0
keyrings.alt                  4.2.0
kgcl-rdflib                   0.5.0
kgcl-schema                   0.5.0
kiwisolver                    1.4.4
lark                          1.1.7
lazy_loader                   0.3
linkml                        1.5.6
linkml-dataops                0.1.0
linkml-renderer               0.2.0
linkml-runtime                1.5.5
lxml                          4.9.3
Markdown                      3.4.4
MarkupSafe                    2.1.3
matplotlib                    3.7.1
matplotlib-inline             0.1.6
mccabe                        0.7.0
mergedeep                     1.3.4
mistune                       3.0.1
mkdocs                        1.5.0
mkdocs-material               9.1.20
mkdocs-material-extensions    1.1.1
mkdocs-mermaid2-plugin        0.6.0
more-click                    0.1.2
more-itertools                9.1.0
multidict                     6.0.4
mypy-extensions               1.0.0
natsort                       8.4.0
nbclassic                     1.0.0
nbclient                      0.8.0
nbconvert                     7.6.0
nbformat                      5.9.0
ndex2                         3.5.1
ndx-beadl                     0.1.0                   /Users/mavaylon/Research/NWB/ndx-beadl/src/pynwb
ndx-multichannel-volume       0.1.8                   /Users/mavaylon/Research/NWB/ndx-multichannel-volume/src/pynwb
nest-asyncio                  1.5.6
networkx                      3.1
neuroconv                     0.4.1
nodeenv                       1.8.0
notebook                      6.5.4
notebook_shim                 0.2.3
numcodecs                     0.11.0
numpy                         1.24.3
nwbinspector                  0.4.29
oaklib                        0.5.12
oauthlib                      3.2.2
ols-client                    0.1.4
ontodev-cogs                  0.3.3
ontoportal-client             0.0.4
openpyxl                      3.1.2
overrides                     7.3.1
packaging                     23.1
pandas                        2.0.1
pandocfilters                 1.5.0
pansql                        0.0.1
parse                         1.19.1
parso                         0.8.3
pathspec                      0.11.1
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.5.0
pip                           23.1.2
platformdirs                  3.8.0
pluggy                        1.2.0
ply                           3.11
pre-commit                    3.3.1
prefixcommons                 0.1.12
prefixmaps                    0.1.5
prometheus-client             0.17.0
prompt-toolkit                3.0.39
pronto                        2.5.4
protobuf                      4.23.4
psutil                        5.9.5
ptyprocess                    0.7.0
pure-eval                     0.2.2
pyasn1                        0.5.0
pyasn1-modules                0.3.0
pycodestyle                   2.10.0
pycparser                     2.21
pycryptodomex                 3.18.0
pydantic                      1.10.9
pyflakes                      3.0.1
Pygments                      2.15.1
PyJSG                         0.11.10
pymdown-extensions            10.1
pynwb                         2.3.3+5.g49a4e694.dirty /Users/mavaylon/Research/NWB/pynwb/src
pyout                         0.7.3
pyparsing                     3.1.0
pyproject-api                 1.5.2
pyrsistent                    0.19.3
PyShEx                        0.8.1
PyShExC                       0.9.1
pysolr                        3.9.0
pystow                        0.5.0
pytest                        7.3.1
pytest-cov                    4.0.0
pytest-logging                2015.11.4
python-dateutil               2.8.2
python-json-logger            2.0.7
PyTrie                        0.4.0
pytz                          2023.3
PyWavelets                    1.4.1
PyYAML                        6.0
pyyaml_env_tag                0.1
pyzmq                         25.1.0
qtconsole                     5.4.3
QtPy                          2.3.1
ratelimit                     2.2.1
rdflib                        6.2.0
rdflib-jsonld                 0.6.1
rdflib-shim                   1.0.3
regex                         2023.6.3
requests                      2.31.0
requests-cache                1.1.0
requests-oauthlib             1.3.1
requests-toolbelt             1.0.0
rfc3339-validator             0.1.4
rfc3986-validator             0.1.1
rfc3987                       1.3.8
rsa                           4.9
ruamel.yaml                   0.17.24
ruamel.yaml.clib              0.2.7
ruff                          0.0.265
s3transfer                    0.6.1
schemasheets                  0.1.23
scikit-image                  0.21.0
scipy                         1.10.1
semantic-version              2.10.0
semsimian                     0.1.18
semsql                        0.3.2
Send2Trash                    1.8.2
setuptools                    68.0.0
ShExJSG                       0.8.2
six                           1.16.0
sniffio                       1.3.0
snowballstemmer               2.2.0
sortedcontainers              2.4.0
soupsieve                     2.4.1
sparqlslurper                 0.5.1
SPARQLWrapper                 2.0.0
Sphinx                        6.2.1
sphinx-copybutton             0.5.2
sphinx-gallery                0.13.0
sphinx-rtd-theme              1.2.2
sphinxcontrib-applehelp       1.0.4
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.1
sphinxcontrib-jquery          4.1
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
SQLAlchemy                    2.0.19
SQLAlchemy-Utils              0.38.3
sssom                         0.3.32
sssom-schema                  0.14.0
stack-data                    0.6.2
tabulate                      0.9.0
tenacity                      8.2.2
termcolor                     2.3.0
terminado                     0.17.1
tifffile                      2023.9.18
tinycss2                      1.2.1
tomli                         2.0.1
tornado                       6.3.2
tox                           4.5.1
tqdm                          4.65.0
traitlets                     5.9.0
typing_extensions             4.6.3
tzdata                        2023.3
uri-template                  1.3.0
uritemplate                   4.1.1
url-normalize                 1.4.3
urllib3                       1.26.16
validators                    0.20.0
virtualenv                    20.23.1
watchdog                      3.0.0
wcwidth                       0.2.6
webcolors                     1.13
webencodings                  0.5.1
websocket-client              1.6.1
wheel                         0.40.0
widgetsnbextension            4.0.8
wrapt                         1.15.0
yarl                          1.9.2
zarr                          2.14.2
zarr-checksum                 0.2.9
zipp                          3.15.0

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/neurodatawithoutborders/nwbinspector/issues)?
- [X] To the best of your ability, have you ensured this is a bug within the code that checks the NWBFile, rather than a bug in the NWBFile reader (e.g., [PyNWB](https://github.com/NeurodataWithoutBorders/pynwb) or [MatNWB](https://github.com/NeurodataWithoutBorders/matnwb))?

**Comment by mavaylon1** [comment]
I installed the inspector and ran:
`nwbinspector test.nwb --config DANDI`

**Comment by CodyCBakerPhD** [comment]
Following the DANDI upload instructions: https://www.dandiarchive.org/handbook/13_upload/#data-uploadmanagement-workflow

This ought to be `--config dandi`

Please reopen if still not working after trying that
