### ISSUE TITLE
[Bug]: prompted rate for regular timestamps check not in Hz

### ISSUE THREAD

**Issue by stephprince** [NeurodataWithoutBorders/nwbinspector#466]
### What happened?

The inspector message in [`check_regular_timestamps`](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/6110d444e6b10acb57f80d410985e09ec5d26f4b/src/nwbinspector/checks/time_series.py#L27-L34) prompts the user to specify a rate instead of timestamps if a `TimeSeries` has a constant sampling rate. 

However, the prompted rate is the interval between the timestamps:
```python
rate={time_series.timestamps[1] - time_series.timestamps[0]}
```
I think the rate should instead be the inverse of the interval between timestamps (1/s) to reflect the sampling rate in Hz that the user would specify when creating a `TimeSeries`?
```python
rate={1 / (time_series.timestamps[1] - time_series.timestamps[0])}"
```

### Operating System

M1 macOS

### Python Version

3.12

### Were you streaming with ROS3?

No

### Package Versions

<details> Copy and paste your output here </details>

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this bug was not already [reported](https://github.com/neurodatawithoutborders/nwbinspector/issues)?
- [X] To the best of your ability, have you ensured this is a bug within the code that checks the NWBFile, rather than a bug in the NWBFile reader (e.g., [PyNWB](https://github.com/NeurodataWithoutBorders/pynwb) or [MatNWB](https://github.com/NeurodataWithoutBorders/matnwb))?

**Comment by CodyCBakerPhD** [comment]
Ooops, thought we fixed this a while back

@stephprince are you willing to make a PR for this?

**Comment by stephprince** [comment]
yes I can make a PR for this!
