### ISSUE TITLE
[Feature]: New release?

### ISSUE THREAD

**Issue by rly** [NeurodataWithoutBorders/nwbinspector#526]
### What would you like to see added to the NWBInspector?

It would be nice to have a new 0.6.0 release soon that includes bug fixes, but I have not been following all of the discussion across issues and PRs. Is the repo in a stage where a new release can be made soon?

### Do you have any interest in helping implement the feature?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this feature was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by stephprince** [comment]
Yes, I think we can do the new release soon to include the bug fixes.

The main additional item that we might want to include were some soft deprecations (mainly submodule imports) that were planned to be fully deprecated after 9/15/24. I can get those into 0.6.0 or include them in the following release.

**Comment by rly** [comment]
Great, thanks!
