### ISSUE TITLE
Do we need both license and Legal?

### ISSUE THREAD

**Issue by CodyCBakerPhD** [NeurodataWithoutBorders/nwbinspector#57]
@oruebel @bendichter 

Two files in repo

https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/Legal.txt

and

https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/license.txt

do we need them both?

**Comment by oruebel** [comment]
I think the Legal.txt can be removed
