### ISSUE TITLE
Provide "structured" machine readable output/return 

### ISSUE THREAD

**Issue by yarikoptic** [NeurodataWithoutBorders/nwbinspector#77]
A companion to #76 but largely orthogonal.

Although we have not standardized in dandi-cli much either, and having looked into nwbinspector insides, but keeping in mind https://github.com/dandi/dandi-cli/issues/924, i.e. integration with dandi-cli, I think it would be great if internally all the "hints/warnings/whatever" were represented as some basic data structure (well -- `dict`) so from CLI I could request just a dump of those hints in machine readable form (e.g. JSON). Default "rendered" of the output could format them as it does now.  And then dandi-cli code could use nwbinspector as a library and just get a list of those records for the path(s) it inquire about.

To some degree such an idea of "alternative output formats" could be seen in `dandi ls --format` option which provides a range of those.  Also, `datalad` inspired folks could use `-f` with any datalad command ;)

**Comment by bendichter** [comment]
Yes we are doing this too 

Edit: well we currently have a Python function that outputs a list of InspectorMessage objects. We could also output them in json if that's easier

**Comment by CodyCBakerPhD** [comment]
> To some degree such an idea of "alternative output formats" could be seen in dandi ls --format option which provides a range of those. Also, datalad inspired folks could use -f with any datalad command ;)

We do plan on eventually offering other save formats. 

> We could also output them in json if that's easier

Indeed, JSON and/or YAML could be among these additional future formats.

> Edit: well we currently have a Python function that outputs a list of InspectorMessage objects. 

Before the recent restructuring to include `pynwb.validate` and full error tracebacks into the report, the primary function that does the heavy lifting ([inspect_nwb](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/nwbinspector/nwbinspector.py#L103-L110)) did return a simple flat list of `InspectorMessage` objects, defined as

```python
@dataclass
class InspectorMessage:
    message: str
    severity: Severity
    importance: Importance
    check_function_name: str
    object_type: str
    object_name: str
    location: str
```

which is the fully portable machine-readable construct that contains the information about the best practice violation.

Now, however, it returns something slightly more structured:

```python
    organized_result = OrderedDict()
    for importance_level, results in unorganized_results.items():
        if any(results):
            organized_result.update({importance_level: results})
    organized_result = {nwbfile_path: organized_result}
    return organized_result
```

which as you can see results in a dictionary; the first key is the path to an NWBFile that was checked and its value is an ordered dictionary whose keys are descending orders of importance levels for check violations that were found on that NWBFile, and the value for each of those is the list of actual `InspectorMessages`.

If you think that structure is too complex for your needs we can also discuss having an option to return the flattened results per NWBFile.

**Comment by bendichter** [comment]
It seems like converting this structure to json would work fine
