### ISSUE TITLE
[Add Check]: validating video files under external_file attribute. 

### ISSUE THREAD

**Issue by Saksham20** [NeurodataWithoutBorders/nwbinspector#87]
### What would you like to see added to the NWBInspector?

Video files that are linked to nwbfiles under `ImageSeries.external_file` should be inspected for:
- Checking their existence on disk with the path specified. (warning importance high). This check would defer for paths for local disk location vs urls. 
- Whether video files are of the common formats: .avi, .mp4, .mov, .wmv, .flv. This can be a mild recommendation (low importance)
- if external_file is a local path, checking if its an absolute or relative to nwbfile location (low importance)

### Pseudocode or other logic of the check

```shell
from pathlib import Path
import requests

video_file_path = "documents/folder0/video0.mp4"
video_file_url = "https://dandiarchive.s3.amazonaws.com/blobs/a52/253/a5225398-ec1c-4325-8bbe-83dc73fa8c87"

def video_exist_check(video_path, nwbfile_path):
   video_path_type = video_pathtype_check_absolute(video_path)
   if  video_path_type == "relative":
      pt = Path(nwbfile_path)/Path(video_path)
      return pt.exists()
   elif video_path_type == "url":
      return requests.head(video_path).ok
   else:
      return Path(video_path).exists()

def video_format_check(video_path):
   if Path(video_path).suffix in [".mp4", ".avi", ".wmv", ".mov", ".flv"]:
      return True
   else:
      return False

def video_pathtype_check_absolute(video_path):
   if os.path.isabs(video_path):
      return "absolute"
   elif any([str(video_path).startswith(i) for i in ["ftp://", "http://", "https://"]]):
      return "url"
   else:
      return "relative"
```

### Do you have any interest in helping implement the check function?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this check was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by CodyCBakerPhD** [comment]
For starters, I think we can extend a couple of these checks to any object that uses external links.

> Checking their existence on disk with the path specified. (warning importance high). This check would defer for paths for local disk location vs urls.

Yeah, that would be great for any object that can and does have external links specified. What are some other objects that can currently support external links?

> if external_file is a local path, checking if its an absolute or relative to nwbfile location (low importance)

Similar to the above, this would also be good to check for any external link. The reasoning of course is that for (a) cross-platform sharing of NWBFiles the first few fields of any absolute path will differ, (b) If the nesting of the absolute path is somewhat deep and specific, even users on the same platform will encounter issues from folder discrepancies, and finally (c) DANDI will outright require this.

@bendichter Can we add this one to the official Best Practices documentation?

> Whether video files are of the common formats: .avi, .mp4, .mov, .wmv, .flv. This can be a mild recommendation (low importance)

This is the only one specific to `ImageSeries`, however, I do think the core checks here on NWBInspector should be the most generous we can possibly be (i.e., any video format that can be opened by any external video viewer). Can you compile a list of all such suffixes? Note that I do not refer here only to the ones openable by OpenCV or other tools.

**Comment by CodyCBakerPhD** [comment]
Otherwise I see that you are interested in contributing these yourself: please read the new Contributions instructions here https://github.com/NeurodataWithoutBorders/nwbinspector/pull/85

**Comment by CodyCBakerPhD** [comment]
Should also add a Best Practice section for ImageSeries data stipulating that order of color channels be "RGB", since we know now that OpenCV uses a different default than is standard for DLC/Scikit

**Comment by bendichter** [comment]
This is explicitly defined in the schema, and I'm not sure how we would automatically check for this

**Comment by CodyCBakerPhD** [comment]
> This is explicitly defined in the schema, and I'm not sure how we would automatically check for this

Oh, I don't think we can automatically check for it, that's why I'm only suggesting adding as Best Practice. But adding it to the schema (if missing) would be even better.

The PyNWB docs for ImageSeries don't mentioned RGB unless I'm not seeing it: https://pynwb.readthedocs.io/en/stable/pynwb.image.html#pynwb.image.ImageSeries

It is mentioned in the RGBImage type, ImageMaskSeries, and OpticalSeries, though.

And where is it defined in the schema for ImageSeries? https://nwb-schema.readthedocs.io/en/latest/format.html?highlight=ImageSeries#sec-imageseries

**Comment by bendichter** [comment]
@CodyCBakerPhD you're right, it doesn't mention color channels at all. This would be a good issue to bring up on the schema repo

**Comment by CodyCBakerPhD** [comment]
Issues raised upstream, then
