### ISSUE TITLE
[Add Check]: ElectricalSeries.electrodes points to the electrodes table

### ISSUE THREAD

**Issue by bendichter** [NeurodataWithoutBorders/nwbinspector#88]
### What would you like to see added to the NWBInspector?

Also, RoiResponseSeries.rois points to a PlaneSegmentation table

### Do you have any interest in helping implement the check function?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this check was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by CodyCBakerPhD** [comment]
@bendichter I think this got closed automatically by a PR that did something similar for `ophys`

Is this still a check you want to have added?

**Comment by bendichter** [comment]
yes, we still need to add the ecephys check. It's a bit different, since "electrodes" doesn't have a dedicated neurodata_type
