### ISSUE TITLE
[Documentation]: Update issue/PR labels to follow the organization default lables

### ISSUE THREAD

**Issue by oruebel** [NeurodataWithoutBorders/nwbinspector#98]
### What would you like changed or added to the documentation and why?

https://github.com/organizations/NeurodataWithoutBorders/settings/repository-defaults

### Do you have any interest in helping write or edit the documentation?

Yes.

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/NeurodataWithoutBorders/nwbinspector/blob/dev/.github/CODE_OF_CONDUCT.rst)
- [X] Have you ensured this change was not already [requested](https://github.com/neurodatawithoutborders/nwbinspector/issues)?

**Comment by CodyCBakerPhD** [comment]
The link https://github.com/organizations/NeurodataWithoutBorders/settings/repository-defaults shows up as a 404 page not found for me. But if you just want the labels to match the global repos under the NeurodataWithoutBorders family, sure I can do that

**Comment by CodyCBakerPhD** [comment]
Done; HDMF and validator topics don't make much sense here so excluded those. We also have an extra category here specific to issues/PRs devoted to new checks or new best practices, separate from bigger picture project features

**Comment by oruebel** [comment]
Perfect! Thanks for doing this!
